### PR TITLE
Fix #48

### LINKED ISSUE #48: `Attrbute.Hook` is incorrect
Hello!

As I was parsing `Attribute` instances, I noticed that the value pointed to by `Hook` was always `0`. When debugging at the point in the code where the `Hook` value is extracted, it seems like the index is wrong -- see the attached screenshot. The index should be `2` instead of `3`?

screenshot

### PR DESCRIPTION
**Pull request by vphpersson**
Use the correct index for the extraction of the hook attribute value.

### CODE REVIEW

**Comment by vphpersson** [comment]
My guess is that the code has in fact worked for you, but endianess is causing the code not to work for me. In that case the solution needs to be a little bit more complicated. Maybe something like this?

```
var hookIndex int
if nativeEndian == binary.LittleEndian {
	hookIndex = 2
} else {
	hookIndex = 3
}
hook := ad.Bytes()[hookIndex]
a.Hook = &hook
```

File: attribute.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ func extractAttribute(a *Attribute, logger Logger, data []byte) error {
 		case nfUlaAttrPacketHdr:
 			hwProtocol := binary.BigEndian.Uint16(ad.Bytes()[:2])
 			a.HwProtocol = &hwProtocol
-			hook := uint8(ad.Bytes()[3])
+			hook := uint8(ad.Bytes()[2])
```
Comment (florianl) [inline attribute.go:25]: Just checked the backing structure on the Kernel side.
https://github.com/torvalds/linux/blob/fac04efc5c793dccbd07e2d59af9f90b7fc0dca4/include/uapi/linux/netfilter/nfnetlink_log.h#L19-L23

Not sure why this indexing bug hasn't been noticed so far. Thanks for idenfying and fixing it!

Can you also update the tests, then I will merge your fix.

Comment (vphpersson) [reply attribute.go:25]: No worries. Thanks for the library!

I have updated the tests. Instead of checking for `0x00` they are now checking for `0x03` and 0x01` respectively, which is maybe what you intended originally? Testing for the zero value seems unsound.

The solution proposed originally is fine? You are sure this has nothing to do with endianess?
